{{- if and .Values.minio.enabled (not .Values.minio.external) }}
apiVersion: v1
kind: Secret
metadata:
  name: argo-workflows-minio-secret
  namespace: {{ include "argo-workflows.namespace" . }}
  labels:
    {{- include "argo-workflows.minio.labels" . | nindent 4 }}
type: Opaque
data:
  accesskey: {{ .Values.minio.auth.rootUser | default "minio-admin" | b64enc }}
  secretkey: {{ .Values.minio.auth.rootPassword | default "minio-admin" | b64enc }}
{{- end }}