{{- if .Values.rbac.create }}
apiVersion: v1
kind: Secret
metadata:
  name: {{ include "argo-workflows.serviceAccountName" . }}.service-account-token
  namespace: {{ include "argo-workflows.namespace" . }}
  labels:
    {{- include "argo-workflows.labels" . | nindent 4 }}
  annotations:
    kubernetes.io/service-account.name: {{ include "argo-workflows.serviceAccountName" . }}
type: kubernetes.io/service-account-token
---
apiVersion: v1
kind: Secret
metadata:
  name: {{ include "argo-workflows.serviceAccountName" . }}-server.service-account-token
  namespace: {{ include "argo-workflows.namespace" . }}
  labels:
    {{- include "argo-workflows.server.labels" . | nindent 4 }}
  annotations:
    kubernetes.io/service-account.name: {{ include "argo-workflows.serviceAccountName" . }}-server
type: kubernetes.io/service-account-token
{{- end }}
