{{- if and .Values.monitoring.enabled .Values.monitoring.prometheus.enabled .Values.monitoring.prometheus.serviceMonitor.enabled }}
apiVersion: monitoring.coreos.com/v1
kind: ServiceMonitor
metadata:
  name: {{ include "argo-workflows.fullname" . }}-controller
  namespace: {{ include "argo-workflows.namespace" . }}
  labels:
    {{- include "argo-workflows.controller.labels" . | nindent 4 }}
    {{- with .Values.monitoring.prometheus.serviceMonitor.additionalLabels }}
    {{- toYaml . | nindent 4 }}
    {{- end }}
spec:
  selector:
    matchLabels:
      app: workflow-controller
      {{- include "argo-workflows.selectorLabels" . | nindent 6 }}
  endpoints:
  - port: metrics
    path: {{ .Values.monitoring.prometheus.serviceMonitor.path }}
    interval: {{ .Values.monitoring.prometheus.serviceMonitor.interval }}
  {{- with .Values.monitoring.prometheus.serviceMonitor.namespaceSelector }}
  namespaceSelector:
    {{- toYaml . | nindent 4 }}
  {{- end }}
---
{{- if .Values.argo.workflows.server.enabled | default true }}
apiVersion: monitoring.coreos.com/v1
kind: ServiceMonitor
metadata:
  name: {{ include "argo-workflows.fullname" . }}-server
  namespace: {{ include "argo-workflows.namespace" . }}
  labels:
    {{- include "argo-workflows.server.labels" . | nindent 4 }}
    {{- with .Values.monitoring.prometheus.serviceMonitor.additionalLabels }}
    {{- toYaml . | nindent 4 }}
    {{- end }}
spec:
  selector:
    matchLabels:
      app: argo-server
      {{- include "argo-workflows.selectorLabels" . | nindent 6 }}
  endpoints:
  - port: metrics
    path: /metrics
    interval: {{ .Values.monitoring.prometheus.serviceMonitor.interval }}
  {{- with .Values.monitoring.prometheus.serviceMonitor.namespaceSelector }}
  namespaceSelector:
    {{- toYaml . | nindent 4 }}
  {{- end }}
{{- end }}
{{- end }}
{{- if and .Values.argo.events.enabled .Values.monitoring.enabled .Values.monitoring.prometheus.enabled .Values.monitoring.prometheus.serviceMonitor.enabled }}
---
apiVersion: monitoring.coreos.com/v1
kind: ServiceMonitor
metadata:
  name: {{ include "argo-workflows.fullname" . }}-events
  namespace: {{ include "argo-workflows.namespace" . }}
  labels:
    {{- include "argo-workflows.events.labels" . | nindent 4 }}
    {{- with .Values.monitoring.prometheus.serviceMonitor.additionalLabels }}
    {{- toYaml . | nindent 4 }}
    {{- end }}
spec:
  selector:
    matchLabels:
      app: argo-events-controller-manager
      {{- include "argo-workflows.selectorLabels" . | nindent 6 }}
  endpoints:
  - port: metrics
    path: /metrics
    interval: {{ .Values.monitoring.prometheus.serviceMonitor.interval }}
  {{- with .Values.monitoring.prometheus.serviceMonitor.namespaceSelector }}
  namespaceSelector:
    {{- toYaml . | nindent 4 }}
  {{- end }}
{{- end }}
