{{ if .Values.stageInOut.enabled }}
apiVersion: v1
kind: Secret
metadata:
  name: user-settings-stage-in-out
type: Opaque
data:
  user-settings.json: {{ tpl (.Values.stageInOut.userSettings | default (.Files.Get "files/user-settings.json")) . | b64enc | quote }}
{{ end }}
